FROM node:10.2.1

WORKDIR /usr/src/app

COPY package*.json tsconfig.json ./
COPY . .

RUN npm install -g typescript
RUN npm install --only=production
RUN npm run build
RUN mkdir -p logs
RUN ls

ENV NODE_ENV production
